# Generated by Django 3.1.4 on 2021-06-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('modelNumber', models.CharField(max_length=60)),
                ('available', models.IntegerField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
            ],
        ),
    ]
